version: '3'

services:

  minako:
    image: node
    environment:
        - CMS_PORT=1340
        - NODE_ENV=production
        - SECRET=e9#9dFXy
        - PASSWORD=ZG<fz9Dh
        - USERNAME=admin
    ports:
        - 1340:1340
    expose: [1340]

    volumes:
        - ./minako:/home/minako

    working_dir: /home/minako
    # tty: true
    command: bash -c "npm install && npm run build && npm run prod" 

  frontend:
    image: node
    restart: unless-stopped
    environment:
        - CMS_PORT=1340
        - PORT=3003
        - NODE_ENV=production
    ports:
        - 3003:3003
    expose: [3003]
    command: "npm run prod"
    working_dir: /var/www/public_html/rike.dev

    volumes:
      - ./frontend/next-app:/var/www/public_html/rike.dev
