version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - mongo:mongo
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - ./db:/data/db
    ports:
      - '27018:27017'

  frontend:
    image: node
    restart: unless-stopped
    links:
      - strapi:strapi
    environment:
        - PORT=3003
        - NODE_ENV=production
    ports:
        - 3003:3003
    command: "npm run prod"
    working_dir: /var/www/public_html/rike.dev

    volumes:
      - ./frontend/next-app:/var/www/public_html/rike.dev
